# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/V15.4/0v7670/0v7670.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/V15.4/0v7670/0v7670.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/Users/admin/V15.4/0v7670/0v7670.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/admin/V15.4/0v7670/0v7670.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/FNTSDZZILV7T645.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/FQTSFQ5ILV7T63Z.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/F5IR32HILV7T64J.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/FLW9TWWILV7T64G.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/FN0FBA2ILV7T649.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/F0UU05JILV7T644.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/F6SJNRTILV7T642.vhd
  C:/Users/admin/V15.4/0v7670/0v7670.srcs/sources_1/imports/Downloads/FZTEBUMILV7T646.vhd
}
read_xdc C:/Users/admin/V15.4/0v7670/0v7670.srcs/constrs_1/imports/Downloads/F5QMAYQILV7T6TF.xdc
set_property used_in_implementation false [get_files C:/Users/admin/V15.4/0v7670/0v7670.srcs/constrs_1/imports/Downloads/F5QMAYQILV7T6TF.xdc]

synth_design -top ov7670_top -part xc7z020clg484-1
write_checkpoint -noxdef ov7670_top.dcp
catch { report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb }
