# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
# IP: The module: 'system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
# IP: The module: 'system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lina/Dokumente/TUB/SoSe2018/AES/audio_game/audio_game.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
